import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PostProvider from "@/providers/PostProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-amber-950 text-white flex justify-center items-center py-10">
          Header
        </header>
        <div className="flex gap-4">
          <div className="bg-slate-400 text-black w-[10%]">
            <p>Side Bar</p>
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/about">About</a>
              </li>
              <li>
                <a href="/blog">blog</a>
              </li>
            </ul>
          </div>
          <div className="w-[70%]">
            <PostProvider>{children}</PostProvider>
          </div>
        </div>
        <footer className="bg-amber-200 text-black flex justify-center items-center py-10">
          Footer
        </footer>
      </body>
    </html>
  );
}
